import type { PipelineResult } from '../core/pipeline.ts';
import type { Finding, FindingGroup } from '../core/finding.ts';
import {
  buildSeverityBuckets,
  categoryIcon,
  collectPipelineFindings,
  countBySeverity,
  formatDuration,
  severityIcon,
  severityLabel,
  SEVERITY_ORDER,
} from './report-model.ts';

export function renderMarkdownReport(result: PipelineResult): string {
  const out: string[] = [];
  const allFindings = collectPipelineFindings(result.consensus.groups, result.consensus.unique);
  const severityCounts = countBySeverity(allFindings);
  const agreedCount = result.consensus.groups.length;
  const uniqueCount = result.consensus.unique.length;

  out.push(`# 🧭 Quorum review — ${escapeMd(result.pipelineId)}`);
  out.push('');
  out.push(
    [
      `**${result.reviews.length} reviewer(s)**`,
      `**${allFindings.length} finding(s)**`,
      `**${agreedCount} agreement group(s)**`,
      `**${uniqueCount} single-reviewer finding(s)**`,
      `**${result.errors.length} error(s)**`,
      `**${formatDuration(result.durationMs)}**`,
    ].join(' · '),
  );
  out.push('');
  out.push('## 📊 Summary');
  out.push('');
  if (result.verdictSummary) {
    out.push(`**Plan verdict:** ${escapeMd(result.verdictSummary.decision.toUpperCase())}`);
    out.push('');
    out.push('| Decision | Reviewers |');
    out.push('| --- | ---: |');
    out.push(`| Approve | ${result.verdictSummary.counts.approve} |`);
    out.push(`| Revise | ${result.verdictSummary.counts.revise} |`);
    out.push(`| Block | ${result.verdictSummary.counts.block} |`);
    out.push('');
  }
  out.push('| Severity | Findings |');
  out.push('| --- | ---: |');
  for (const severity of SEVERITY_ORDER) {
    out.push(`| ${severityIcon(severity)} ${severityLabel(severity)} | ${severityCounts[severity]} |`);
  }
  out.push('');

  if (result.errors.length > 0) {
    out.push('## 🚨 Reviewer errors');
    for (const e of result.errors) out.push(`- **${escapeMd(e.reviewerId)}**: ${escapeMd(e.message)}`);
    out.push('');
  }

  if (result.verdictSummary?.summaries.length) {
    out.push('## 🧾 Reviewer verdicts');
    for (const verdict of result.verdictSummary.summaries) {
      const confidence = verdict.confidence ? ` · confidence: ${verdict.confidence}` : '';
      out.push(`- **${escapeMd(verdict.reviewerId)}**: ${escapeMd(verdict.decision)}${escapeMd(confidence)} — ${escapeMd(verdict.summary)}`);
    }
    out.push('');
  }

  out.push('## 💰 Token Usage');
  out.push('');
  let totalInput = 0;
  let totalOutput = 0;
  let totalCost = 0;
  let hasCost = false;
  for (const review of result.reviews) {
    if (!review.usage) continue;
    totalInput += review.usage.inputTokens;
    totalOutput += review.usage.outputTokens;
    if (review.usage.costUsd !== undefined) {
      totalCost += review.usage.costUsd;
      hasCost = true;
    }
  }
  if (totalInput > 0 || totalOutput > 0) {
    out.push(`| Reviewer | Input Tokens | Output Tokens | ${hasCost ? 'Cost' : ''}`);
    out.push(`| --- | ---: | ---: |${hasCost ? ' ---:' : ''}`);
    for (const review of result.reviews) {
      if (!review.usage) {
        out.push(`| ${escapeMd(review.reviewerId)} | _no data_ | _no data_ |${hasCost ? ' _no data_' : ''}`);
        continue;
      }
      const cost = review.usage.costUsd !== undefined ? `$${review.usage.costUsd.toFixed(4)}` : '—';
      out.push(`| ${escapeMd(review.reviewerId)} | ${review.usage.inputTokens.toLocaleString()} | ${review.usage.outputTokens.toLocaleString()} |${hasCost ? ` ${cost}` : ''}`);
    }
    out.push(`| **Total** | **${totalInput.toLocaleString()}** | **${totalOutput.toLocaleString()}** |${hasCost ? ` **$${totalCost.toFixed(4)}**` : ''}`);
    out.push('');
  } else {
    out.push('_No token usage data available._');
    out.push('');
  }

  out.push('## 🔎 Findings by priority');
  renderPriorityFindings(out, result.consensus.groups, result.consensus.unique);

  out.push('');
  out.push('---');
  out.push(`*Generated by quorum · consensus strategy: ${escapeMd(result.consensus.strategyId)}*`);
  return out.join('\n');
}

function renderPriorityFindings(out: string[], groups: FindingGroup[], unique: Finding[]): void {
  if (groups.length === 0 && unique.length === 0) {
    out.push('_No findings._');
    return;
  }

  for (const bucket of buildSeverityBuckets(groups, unique)) {
    if (bucket.count === 0) continue;

    out.push(`### ${severityIcon(bucket.severity)} ${severityLabel(bucket.severity)} (${bucket.count})`);
    for (const g of bucket.groups) renderGroup(out, g);
    for (const f of bucket.unique) renderFinding(out, f);
  }
}

function renderGroup(out: string[], g: FindingGroup): void {
  const f = g.representative;
  out.push(`#### 🤝 ${escapeMd(f.title)}`);
  out.push('');
  out.push(`> ${g.reviewers.length} reviewer(s) agreed · ${g.members.length} matching report(s)`);
  out.push('');
  renderFindingMeta(out, f, `**Reviewers:** ${g.reviewers.map(escapeMd).join(', ')}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function renderFinding(out: string[], f: Finding): void {
  out.push(`#### 👤 ${escapeMd(f.title)}`);
  out.push('');
  renderFindingMeta(out, f, `**Reviewer:** ${escapeMd(f.reviewer)}`);
  out.push('');
  if (f.body) out.push(escapeMd(f.body));
  out.push('');
}

function renderFindingMeta(out: string[], f: Finding, reviewerLine: string): void {
  out.push(`- **Location:** \`${escapeFilePath(f.file)}:${f.lineRange.start}-${f.lineRange.end}\``);
  out.push(`- **Category:** ${categoryIcon(f.category)} ${f.category}`);
  out.push(`- ${reviewerLine}`);
}

function escapeFilePath(p: string): string {
  return p.replace(/`/g, '\\`');
}

function escapeMd(s: string): string {
  return s.replace(/([\\`*_{}[\]()#+\-.!~|<>])/g, '\\$1');
}
